# Generated by Django 5.0.2 on 2024-03-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0002_rename_parttbl_lm_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='part_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PartName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='running_part_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PartName', models.CharField(max_length=255)),
            ],
        ),
    ]
