# Generated by Django 5.0.2 on 2024-03-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0004_rename_partname_running_part_tbl_selected_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='running_part_tbl',
            name='selected_part',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
