# Generated by Django 4.2.9 on 2024-03-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0007_running_part_tbl_prod_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lm_tbl',
            name='PartName',
            field=models.IntegerField(),
        ),
    ]
