# Generated by Django 4.2.9 on 2024-03-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0008_alter_lm_tbl_partname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part_tbl',
            name='PartName',
            field=models.IntegerField(),
        ),
    ]
