# Generated by Django 5.0.2 on 2024-02-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartTbl',
            new_name='lm_tbl',
        ),
    ]
