# Generated by Django 5.0.2 on 2024-03-05 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0003_part_tbl_running_part_tbl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='running_part_tbl',
            old_name='PartName',
            new_name='selected_part',
        ),
    ]
