# Generated by Django 5.0.2 on 2024-03-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0006_rename_selected_part_running_part_tbl_part_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='running_part_tbl',
            name='prod_status',
            field=models.IntegerField(default=0),
        ),
    ]
